mrgoldy_ultimateblog_index:
    pattern: /blog
    defaults: { _controller: mrgoldy.ultimateblog.controller.bloglist:index, page: 1 }

mrgoldy_ultimateblog_subpages:
    resource: "ultimateblog_routing.yml"
    prefix: /blog
