mrgoldy_ultimateblog_indexpage:
    pattern: /page/{page}
    defaults: { _controller: mrgoldy.ultimateblog.controller.bloglist:index }
    requirements:
        page: \d+

mrgoldy_ultimateblog_view:
    pattern: /view/{blog_id}
    defaults: { _controller: mrgoldy.ultimateblog.controller.blog:display }
    requirements:
        blog_id: \d+

mrgoldy_ultimateblog_misc:
    pattern: /view/{blog_id}/{mode}
    defaults: { _controller: mrgoldy.ultimateblog.controller.posting:misc }
    requirements:
        blog_id: \d+

mrgoldy_ultimateblog_posting:
    pattern: /posting/{mode}/{blog_id}
    defaults: { _controller: mrgoldy.ultimateblog.controller.posting:handle, blog_id: 0 }
    requirements:
        blog_id: \d+

mrgoldy_ultimateblog_report:
    pattern: /report/{blog_id}/{mode}/{id}
    defaults: { _controller: mrgoldy.ultimateblog.controller.report:handle }
    requirements:
        blog_id: \d+
        id: \d+

mrgoldy_ultimateblog_categories:
    pattern: /categories
    defaults: { _controller: mrgoldy.ultimateblog.controller.categories:overview, page: 1 }

mrgoldy_ultimateblog_categoriespage:
    pattern: /categories/page/{page}
    defaults: { _controller: mrgoldy.ultimateblog.controller.categories:overview }
    requirements:
        page: \d+

mrgoldy_ultimateblog_category:
    pattern: /category/{category_id}
    defaults: { _controller: mrgoldy.ultimateblog.controller.bloglist:category, page: 1 }
    requirements:
        category_id: \d+

mrgoldy_ultimateblog_categorypage:
    pattern: /category/{category_id}/page/{page}
    defaults: { _controller: mrgoldy.ultimateblog.controller.bloglist:category }
    requirements:
        category_id: \d+
        page: \d+

mrgoldy_ultimateblog_archives:
    pattern: /archives
    defaults: { _controller: mrgoldy.ultimateblog.controller.archives:overview }

mrgoldy_ultimateblog_archive:
    pattern: /archive/{year}/{month}
    defaults: { _controller: mrgoldy.ultimateblog.controller.bloglist:archive, page 1 }
    requirements:
        year: \d+
        month: \d+

mrgoldy_ultimateblog_archivepage:
    pattern: /archive/{year}/{month}/page/{page}
    defaults: { _controller: mrgoldy.ultimateblog.controller.bloglist:archive }
    requirements:
        year: \d+
        month: \d+
        page: \d+

mrgoldy_ultimateblog_user:
    pattern: /user/{user_id}
    defaults: { _controller: mrgoldy.ultimateblog.controller.bloglist:user, page 1 }
    requirements:
        user_id: \d+

mrgoldy_ultimateblog_userpage:
    pattern: /user/{user_id}/page/{page}
    defaults: { _controller: mrgoldy.ultimateblog.controller.bloglist:user }
    requirements:
        user_id: \d+
        page: \d+
